# Generated by Django 3.2.4 on 2021-06-17 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2021)], verbose_name='year'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sex',
            field=models.CharField(choices=[('she', 'She/her'), ('he', 'He/him'), ('they', 'They/them'), ('none', 'I prefer not to say')], default='none', max_length=10),
        ),
    ]
