# Generated by Django 3.2.4 on 2021-06-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_auto_20210620_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
